/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sat;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author jorge.l
 */
public class asesor extends javax.swing.JFrame {
    
        Connection con=null;
        Statement stmt=null;
        String var,var2;
        boolean bandera =true;
    /**
     * Creates new form asesor
     */
    public asesor() {
        initComponents();
        this.setTitle("Registro Asesor");
        this.setLocation(400,200);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_horaAsesoria = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        btn_regresa = new javax.swing.JButton();
        txt_cubo = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        crearLista = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UACM.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 190, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("registro de asesores de tesis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("correo electronico:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("nombre  :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("horario de asesorias :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("cubiculo :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, 20));

        txt_horaAsesoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_horaAsesoriaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_horaAsesoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 130, -1));

        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, -1));

        btn_regresa.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_regresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        btn_regresa.setText("regresar");
        btn_regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 170, 70));
        getContentPane().add(txt_cubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 130, -1));

        btn_aceptar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.jpg"))); // NOI18N
        btn_aceptar.setText("aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 30));

        crearLista.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        crearLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearlista.png"))); // NOI18N
        crearLista.setText("crear lista");
        crearLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearListaActionPerformed(evt);
            }
        });
        getContentPane().add(crearLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 140, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyTyped
        char c =evt.getKeyChar();//condicion para la entrada de solo caracteres
       if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ')){
           evt.consume();
       }
    }//GEN-LAST:event_txt_nomKeyTyped

    private void txt_horaAsesoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_horaAsesoriaKeyTyped
         char c =evt.getKeyChar();
      if((c<'0'||c>'9')&&(c<':'||c>':')){
          evt.consume();
      }
    }//GEN-LAST:event_txt_horaAsesoriaKeyTyped

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
         String cadena2,cadena3,cadena4,cadena5;
        // obtener texto de los campos  de texfield
        cadena2 = txt_nom.getText();
        cadena3 = txt_cubo.getText();
        cadena4 = txt_correo.getText();
        cadena5 = txt_horaAsesoria.getText();
        
                      //revisar que los campos no esten vacios 
          
                    if (txt_nom.getText().equals("") || (txt_cubo.getText().equals(""))
                    || (txt_correo.getText().equals("")) || (txt_horaAsesoria.getText().equals(""))) {
            
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","¡AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txt_nom.requestFocus();
            bandera=false;
        }
        
    
                    
        else {
        
            try {
           //enlase a base de datos  en mysql
           //agregar libreria clik derecho addJAR/folder
           //se agrega  mysql-conector-java-bin.jar
            String url = "jdbc:mysql://localhost:3306/sat";
            String usuario = "root";
            String contraseña = "root";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
                  stmt = con.createStatement(); 
                  stmt.executeUpdate("INSERT INTO asesor VALUES('" + 0 + "','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
                 
                   //exeption
        } catch (InstantiationException ex) {
           Logger.getLogger(asesor.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           Logger.getLogger(asesor.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(asesor.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(asesor.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
         bandera=true;
      }
                       
        //inicializa datos despues de registrar            
        
        if(bandera==true){
        
        this.txt_nom.setText("");
        this.txt_cubo.setText("");
        this.txt_correo.setText("");
        this.txt_horaAsesoria.setText("");
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresaActionPerformed
         this.dispose();//oculta
        logueo p= new logueo();//instancia de la clase 
        p.setVisible(true);//lo hace visible
                                               
    }//GEN-LAST:event_btn_regresaActionPerformed

    private void crearListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearListaActionPerformed
        this.dispose();
        creaLista us= new creaLista();
        us.setVisible(true);
    }//GEN-LAST:event_crearListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_regresa;
    private javax.swing.JButton crearLista;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_cubo;
    private javax.swing.JTextField txt_horaAsesoria;
    private javax.swing.JTextField txt_nom;
    // End of variables declaration//GEN-END:variables
}
